### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by arunumap** [SendGridJP/smtpapi-ruby#11]
I've been on sendgrid tech support for over 3.5 hours and we can't figure this out.  He recommended I post my error on here.  Here it is.

I am sending out approximately 35K emails.  After about 30K emails successfully sent (1000 emails at a time using x-smtpapi header), I am getting a 400 bad request for response.code and the message is "{\"message\": \"error\", \"errors\": [\"JSON in x-smtpapi could not be parsed\"]}".

I am not sure if the Json is being validated on the client side because according to support, I should have gotten an email specifying where the json issue is, I have not gotten this email.  I also am unsure how 30K emails can be successfully sent and then it breaking giving me the error unless there is some encoding issue with an email address.

Please advise, any help is greatly appreciated.

**Comment by awwa** [comment]
I'm not sure the cause of problem.
But I fixed a problem on new version of smtpapi-ruby 0.0.11.
It handles a small value of Unicode properly.
Could you please try it?  `bundle update`

If you get the error 400 after that, could you please show the request value of x-smtpapi you sent?
